name: Push Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'package.zip'

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
            artifacts: "package.zip"
            token: ${{ secrets.GITHUB_TOKEN }}
